# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build-test-and-publish-container: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - uses: azure/docker-login@v1 
        with: 
          login-server: idi2019.azurecr.io 
          username: ${{ secrets.IDI2019_REGISTRY_USERNAME }} 
          password: ${{ secrets.IDI2019_REGISTRY_PASSWORD }} 
      - name: build and publish container 
        run: |
            chmod +x ./build.sh
            ./build.sh
