# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build
        run: dotnet build
      - uses: actions/setup-dotnet@v1 
        with: 
          dotnet-version: '5.0.x'
      - name: containerBuild
      
      - name: build-test-and-publish-container: 
        runs-on: ubuntu-latest 
        steps: 
          - uses: actions/checkout@v2 
          - uses: azure/docker-login@v1 
            with: 
              login-server: idi2019.azurecr.io 
              username: ${{ secrets.IDI2019_REGISTRY_USERNAME }} 
              password: ${{ secrets.IDI2019_REGISTRY_PASSWORD }} 
          - name: build project 
            run: make 
          - name: build and publish container 
            run: ./build.sh build-$GITHUB_RUN_NUMBER idi2019.azurecr.io
